//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<int> CheckIdDonor { get; set; }
        public Nullable<int> CheckIdAcceptor { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Money { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Check Check1 { get; set; }
    }
}
